import { NextResponse } from "next/server";

const TOP_PRODUCTS = [
  {
    id: "prod_1001",
    name: "Wireless Bluetooth Headphones",
    image: "/images/products/product_1.jpg",
    price: 149.99,
    quantity: 1250,
    revenue: 187487,
    category: "Electronics",
    growth: 24.5,
    rank: 1,
  },
  {
    id: "prod_1002",
    name: "Smart Watch Pro Max",
    image: "/images/products/product_2.jpg",
    price: 299.99,
    quantity: 980,
    revenue: 293990,
    category: "Electronics",
    growth: 18.3,
    rank: 2,
  },
  {
    id: "prod_1003",
    name: "Organic Cotton T-Shirt",
    image: "/images/products/product_3.jpg",
    price: 39.99,
    quantity: 4200,
    revenue: 167958,
    category: "Fashion",
    growth: 32.1,
    rank: 3,
  },
  {
    id: "prod_1004",
    name: "4K Ultra HD Monitor 27\"",
    image: "/images/products/product_4.jpg",
    price: 449.99,
    quantity: 520,
    revenue: 233995,
    category: "Electronics",
    growth: 8.7,
    rank: 4,
  },
  {
    id: "prod_1005",
    name: "Mechanical Gaming Keyboard",
    image: "/images/products/product_5.jpg",
    price: 129.99,
    quantity: 1850,
    revenue: 240481,
    category: "Electronics",
    growth: 15.2,
    rank: 5,
  },
  {
    id: "prod_1006",
    name: "Ergonomic Office Chair",
    image: "/images/products/product_6.jpg",
    price: 349.99,
    quantity: 410,
    revenue: 143496,
    category: "Home & Living",
    growth: 42.8,
    rank: 6,
  },
  {
    id: "prod_1007",
    name: "Portable Solar Charger 20000mAh",
    image: "/images/products/product_7.jpg",
    price: 79.99,
    quantity: 2100,
    revenue: 167979,
    category: "Electronics",
    growth: 56.3,
    rank: 7,
  },
  {
    id: "prod_1008",
    name: "Premium Leather Wallet",
    image: "/images/products/product_8.jpg",
    price: 59.99,
    quantity: 3200,
    revenue: 191968,
    category: "Fashion",
    growth: 11.4,
    rank: 8,
  },
];

export async function GET() {
  return NextResponse.json({
    success: true,
    data: TOP_PRODUCTS,
  });
}
